// <auto-generated />
using System;
using AssetTracker.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssetTracker.Core.Migrations
{
    [DbContext(typeof(AssetTrackerContext))]
    [Migration("20181226190424_AssetLocation")]
    partial class AssetLocation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AssetTracker.Core.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDt");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<byte[]>("Photo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetTracker.Core.Entities.AssetLocation", b =>
                {
                    b.Property<int>("AssetId");

                    b.Property<int>("LocationId");

                    b.Property<DateTime>("CreateDt");

                    b.Property<string>("Note");

                    b.HasKey("AssetId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("AssetLocation");
                });

            modelBuilder.Entity("AssetTracker.Core.Entities.AssetUser", b =>
                {
                    b.Property<int>("AssetId");

                    b.Property<int>("UserId");

                    b.HasKey("AssetId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AssetUser");
                });

            modelBuilder.Entity("AssetTracker.Core.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssetId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AssetTracker.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("NmFirst");

                    b.Property<string>("NmLast");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AssetTracker.Core.Entities.AssetLocation", b =>
                {
                    b.HasOne("AssetTracker.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AssetTracker.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AssetTracker.Core.Entities.AssetUser", b =>
                {
                    b.HasOne("AssetTracker.Core.Entities.Asset", "Asset")
                        .WithMany("AssetUsers")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AssetTracker.Core.Entities.User", "User")
                        .WithMany("AssetUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AssetTracker.Core.Entities.Location", b =>
                {
                    b.HasOne("AssetTracker.Core.Entities.Asset")
                        .WithMany("Locations")
                        .HasForeignKey("AssetId");
                });
#pragma warning restore 612, 618
        }
    }
}
